name: Test templates

on: [push, pull_request]

jobs:
  test_templates:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: set up panc
      run: |
        yum -y install http://yum.quattor.org/devel/quattor-release-1-1.noarch.rpm
        yum -y install panc which maven
    - name: test templates
      run: ./test_templates.sh
